---
title: Loader script for Homework 8
author: Mohamed Elnafe
date: last-modified
format:
  html:
    theme: cosmo
    toc: true
    embed-resources: true
    code-copy: true
execute:
  cache: false
  echo: true
  eval: true
---

# Data sources

```{python}
import pandas as pd
import requests, zipfile, io
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

# Download WDI CSV Zip
url = "https://databank.worldbank.org/data/download/WDI_CSV.zip"
r = requests.get(url)
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall()

# Load extracted files
df_country = pd.read_csv("WDICountry.csv")
df_series = pd.read_csv("WDISeries.csv")
df_data = pd.read_csv("WDICSV.csv")

# Load database credentials
config_map = {
    'user':'CMSC408_admin_user',
    'password':'CMSC408_admin_pass',
    'host':'CMSC408_admin_host',
    'database':'CMSC408_world_bank_db'
}
load_dotenv()
config = {k: os.getenv(v) for k,v in config_map.items()}

# Connect to database
engine = create_engine(f"mysql+pymysql://{config['user']}:{config['password']}@{config['host']}/{config['database']}")

# Upload tables (overwrite!)
df_country.to_sql('wdi_country', engine, if_exists='replace', index=False)
df_series.to_sql('wdi_series', engine, if_exists='replace', index=False)
df_data.to_sql('wdi_data', engine, if_exists='replace', index=False)

print("✅ Data uploaded successfully!")
